"""New Migration

Revision ID: 01daea5116f3
Revises: a85293be57b9
Create Date: 2024-06-29 18:18:28.885270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01daea5116f3'
down_revision: Union[str, None] = 'a85293be57b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_id', table_name='images')
    op.drop_index('ix_images_src', table_name='images')
    op.drop_index('ix_images_title', table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('src', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('package_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.PackageID'], name='images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_images_title', 'images', ['title'], unique=False)
    op.create_index('ix_images_src', 'images', ['src'], unique=False)
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    # ### end Alembic commands ###
