"""SignUp fix

Revision ID: 45dbc087bf0b
Revises: d36b770fbcca
Create Date: 2024-07-13 07:01:23.670933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '45dbc087bf0b'
down_revision: Union[str, None] = 'd36b770fbcca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###
