"""Specify length for String columns in all models

Revision ID: 54f48d3cc1c8
Revises: 16c5b531ec16
Create Date: 2024-08-05 14:41:45.057500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f48d3cc1c8'
down_revision: Union[str, None] = '16c5b531ec16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('packages', sa.Column('StripeProductID', sa.String(length=255), nullable=True))
    op.add_column('packages', sa.Column('StripePriceID', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_SessionID'), 'payments', ['SessionID'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_SessionID'), table_name='payments')
    op.drop_column('packages', 'StripePriceID')
    op.drop_column('packages', 'StripeProductID')
    # ### end Alembic commands ###
