"""Initial migration

Revision ID: 6c0e4ec9cf7b
Revises: c9b5d18bed5e
Create Date: 2024-07-12 15:53:52.180392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6c0e4ec9cf7b'
down_revision: Union[str, None] = 'c9b5d18bed5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attachments_AttachmentID', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_table('attachments',
    sa.Column('AttachmentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('PackageID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('src', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('rawFile', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['PackageID'], ['packages.PackageID'], name='attachments_ibfk_1'),
    sa.PrimaryKeyConstraint('AttachmentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_attachments_AttachmentID', 'attachments', ['AttachmentID'], unique=False)
    # ### end Alembic commands ###
