"""Your description

Revision ID: a85293be57b9
Revises: 
Create Date: 2024-06-29 18:11:02.195466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a85293be57b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('account_activations', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('bookings', 'Status',
               existing_type=mysql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED'),
               type_=sa.Enum('CONFIRMED', 'PENDING', 'CANCELLED', name='bookingstatus'),
               nullable=False)
    op.add_column('images', sa.Column('package_id', sa.Integer(), nullable=True))
    op.drop_index('ix_images_ssrc', table_name='images')
    op.create_index(op.f('ix_images_src'), 'images', ['src'], unique=False)
    op.create_foreign_key(None, 'images', 'packages', ['package_id'], ['PackageID'])
    op.alter_column('users', 'CreatedDate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'UpdatedDate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'UpdatedDate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'CreatedDate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_index(op.f('ix_images_src'), table_name='images')
    op.create_index('ix_images_ssrc', 'images', ['src'], unique=False)
    op.drop_column('images', 'package_id')
    op.alter_column('bookings', 'Status',
               existing_type=sa.Enum('CONFIRMED', 'PENDING', 'CANCELLED', name='bookingstatus'),
               type_=mysql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED'),
               nullable=True)
    op.alter_column('account_activations', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
