"""New Migration

Revision ID: aa5e0634c0c9
Revises: 01daea5116f3
Create Date: 2024-06-30 13:45:23.541986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa5e0634c0c9'
down_revision: Union[str, None] = '01daea5116f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('AttachmentID', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('attachments', sa.Column('PackageID', sa.Integer(), nullable=True))
    op.add_column('attachments', sa.Column('Title', sa.String(length=255), nullable=True))
    op.add_column('attachments', sa.Column('Src', sa.String(length=255), nullable=True))
    op.drop_index('ix_attachments_id', table_name='attachments')
    op.drop_index('ix_attachments_src', table_name='attachments')
    op.drop_index('ix_attachments_title', table_name='attachments')
    op.drop_constraint('attachments_ibfk_1', 'attachments', type_='foreignkey')
    op.create_foreign_key(None, 'attachments', 'packages', ['PackageID'], ['PackageID'])
    op.drop_column('attachments', 'src')
    op.drop_column('attachments', 'package_id')
    op.drop_column('attachments', 'id')
    op.drop_column('attachments', 'raw_file')
    op.drop_column('attachments', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('attachments', sa.Column('raw_file', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('attachments', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('attachments', sa.Column('package_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('src', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'attachments', type_='foreignkey')
    op.create_foreign_key('attachments_ibfk_1', 'attachments', 'packages', ['package_id'], ['PackageID'])
    op.create_index('ix_attachments_title', 'attachments', ['title'], unique=False)
    op.create_index('ix_attachments_src', 'attachments', ['src'], unique=False)
    op.create_index('ix_attachments_id', 'attachments', ['id'], unique=False)
    op.drop_column('attachments', 'Src')
    op.drop_column('attachments', 'Title')
    op.drop_column('attachments', 'PackageID')
    op.drop_column('attachments', 'AttachmentID')
    # ### end Alembic commands ###
