"""Initial migration based on current models

Revision ID: c9b5d18bed5e
Revises: 
Create Date: 2024-07-06 14:07:18.099662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9b5d18bed5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('destinations', 'src',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=1255),
               existing_nullable=True)
    op.alter_column('destinations', 'rawFile',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    op.create_foreign_key(None, 'payments', 'bookings', ['BookingID'], ['BookingID'])
    op.create_foreign_key(None, 'reviews', 'packages', ['PackageID'], ['PackageID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.alter_column('destinations', 'rawFile',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)
    op.alter_column('destinations', 'src',
               existing_type=sa.String(length=1255),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
