"""Add PaymentIntentID

Revision ID: cf8999b20bf4
Revises: 54f48d3cc1c8
Create Date: 2024-08-06 13:50:17.006761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8999b20bf4'
down_revision: Union[str, None] = '54f48d3cc1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('PaymentIntentID', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_PaymentIntentID'), 'payments', ['PaymentIntentID'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_PaymentIntentID'), table_name='payments')
    op.drop_column('payments', 'PaymentIntentID')
    # ### end Alembic commands ###
