"""Update database

Revision ID: eef6b2a9ce20
Revises: 535db2ef754f
Create Date: 2024-08-21 14:54:49.440889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef6b2a9ce20'
down_revision: Union[str, None] = '535db2ef754f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('ErrorMessage', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'ErrorMessage')
    # ### end Alembic commands ###
